import type { SavedFlow } from '@/interfaces';

export const preloadedFlows: SavedFlow[] = [
  {
    id: '4e2d8c1a-6f57-49b3-ae85-7c9f2b3d1a0e',
    projectName: 'Product Development Workflow',
    createdAt: '2025-03-05',
    lastModified: '2025-03-08',
    activities: [
      {
        id: 'f5a3e7c9-2b8d-41e6-9f5a-3c7b8d2e1a4f',
        activityName: 'Requirements Gathering',
        description:
          'Collect and document product requirements from stakeholders',
        inputs: [
          'Market Research',
          'Customer Feedback',
          'Stakeholder Interviews',
        ],
        outputs: ['Requirements Document', 'Feature List'],
        color: '#722ed1',
        assignedUsers: ['Product Manager', 'Business Analyst'],
      },
      {
        id: '9c5e1a7f-4b2d-48e3-a6c9-7f5e3d2b1a8c',
        activityName: 'Design Phase',
        description:
          'Create wireframes and design mockups based on requirements',
        inputs: ['Requirements Document', 'Brand Style Guide'],
        outputs: ['Wireframes', 'UI Mockups', 'Design Specifications'],
        color: '#eb2f96',
        assignedUsers: ['UX Designer', 'UI Designer'],
      },
      {
        id: '2a7e9c5b-1f4d-43e8-b6a2-9d5f1e3c7b4a',
        activityName: 'Development Planning',
        description:
          'Break down requirements into development tasks and estimate effort',
        inputs: ['Requirements Document', 'Design Specifications'],
        outputs: [
          'Development Tasks',
          'Sprint Plan',
          'Technical Specifications',
        ],
        color: '#13c2c2',
        assignedUsers: ['Tech Lead', 'Development Team'],
      },
    ],
  },
  {
    id: '5c8a2b1d-7e6f-49a3-bc5d-8f2a1c9b7e6d',
    projectName: 'Software Testing Workflow',
    createdAt: '2025-03-01',
    lastModified: '2025-03-09',
    activities: [
      {
        id: '7d9e5c2b-1a3f-48d6-b7c9-5e2d1a3f4b8c',
        activityName: 'Test Planning',
        description: 'Create comprehensive test plans and strategies',
        inputs: [
          'Software Requirements',
          'Risk Assessment',
          'Resource Availability',
        ],
        outputs: ['Test Plan', 'Test Strategy', 'Test Schedule'],
        color: '#1890ff',
        assignedUsers: ['Test Manager', 'Test Lead'],
      },
      {
        id: '3b7c9e5a-2d1f-47b6-a3c7-9e5d2b1f4a8c',
        activityName: 'Test Case Development',
        description: 'Create detailed test cases and scenarios',
        inputs: ['Test Plan', 'Software Requirements', 'Design Documents'],
        outputs: ['Test Cases', 'Test Scripts', 'Test Data'],
        color: '#13c2c2',
        assignedUsers: ['Test Analysts', 'Test Engineers'],
      },
      {
        id: '9c5e3b7a-1d2f-48c6-b9c5-e3b7a1d2f4c8',
        activityName: 'Test Environment Setup',
        description: 'Prepare testing environments and tools',
        inputs: [
          'System Architecture',
          'Test Plan',
          'Infrastructure Requirements',
        ],
        outputs: [
          'Test Environment',
          'Testing Tools Configuration',
          'Environment Documentation',
        ],
        color: '#52c41a',
        assignedUsers: ['Test Environment Specialist', 'DevOps Engineer'],
      },
      {
        id: '5b9c7e3a-1f2d-47b6-a5b9-c7e3a1f2d4b6',
        activityName: 'Test Execution',
        description: 'Execute test cases and record results',
        inputs: ['Test Cases', 'Test Environment', 'Test Data'],
        outputs: ['Test Results', 'Defect Reports', 'Test Coverage Report'],
        color: '#faad14',
        assignedUsers: ['Test Engineers', 'Automation Engineers'],
      },
      {
        id: '1f3d5b7c-9e2a-48d6-b1f3-d5b7c9e2a4d6',
        activityName: 'Test Closure',
        description: 'Analyze test results and prepare final reports',
        inputs: ['Test Results', 'Defect Reports', 'Test Coverage Report'],
        outputs: [
          'Test Summary Report',
          'Quality Assessment',
          'Process Improvement Recommendations',
        ],
        color: '#eb2f96',
        assignedUsers: [
          'Test Manager',
          'Test Lead',
          'Quality Assurance Manager',
        ],
      },
    ],
  },

  {
    id: '2b4d6f8a-1c3e-49a7-b2d4-6f8a1c3e5d7b',
    projectName: 'Marketing Campaign Workflow',
    createdAt: '2025-02-15',
    lastModified: '2025-03-07',
    activities: [
      {
        id: '6e8c0a2d-4f9b-47a5-b6e8-c0a2d4f9b7a5',
        activityName: 'Campaign Strategy',
        description: 'Define marketing campaign objectives and strategy',
        inputs: ['Market Research', 'Brand Guidelines', 'Budget Constraints'],
        outputs: [
          'Campaign Brief',
          'Target Audience Profile',
          'Campaign Goals',
        ],
        color: '#722ed1',
        assignedUsers: ['Marketing Director', 'Brand Strategist'],
      },
      {
        id: '0a2c4e6g-8i1k-47m5-b0a2-c4e6g8i1k3m5',
        activityName: 'Content Creation',
        description: 'Develop marketing content for various channels',
        inputs: [
          'Campaign Brief',
          'Brand Guidelines',
          'Target Audience Profile',
        ],
        outputs: ['Marketing Copy', 'Visual Assets', 'Content Calendar'],
        color: '#eb2f96',
        assignedUsers: ['Copywriter', 'Graphic Designer', 'Content Manager'],
      },
      {
        id: '4g6i8k0m-2c4e-47g6-b4g6-i8k0m2c4e6g8',
        activityName: 'Channel Setup',
        description: 'Prepare marketing channels for campaign launch',
        inputs: ['Marketing Copy', 'Visual Assets', 'Campaign Goals'],
        outputs: [
          'Ad Configurations',
          'Social Media Schedules',
          'Email Templates',
        ],
        color: '#fa541c',
        assignedUsers: ['Digital Marketing Specialist', 'Social Media Manager'],
      },
      {
        id: '8k0m2o4q-6s8u-47w6-b8k0-m2o4q6s8u0w2',
        activityName: 'Campaign Launch',
        description: 'Launch campaign across all planned channels',
        inputs: [
          'Ad Configurations',
          'Social Media Schedules',
          'Email Templates',
          'Content Calendar',
        ],
        outputs: ['Live Campaign', 'Initial Metrics', 'Launch Report'],
        color: '#fa8c16',
        assignedUsers: ['Campaign Manager', 'Marketing Team'],
      },
      {
        id: '2o4q6s8u-0w2y-47a6-b2o4-q6s8u0w2y4a6',
        activityName: 'Performance Analysis',
        description: 'Monitor and analyze campaign performance',
        inputs: ['Live Campaign', 'Initial Metrics', 'Launch Report'],
        outputs: [
          'Performance Report',
          'ROI Analysis',
          'Optimization Recommendations',
        ],
        color: '#52c41a',
        assignedUsers: ['Marketing Analyst', 'Marketing Director'],
      },
    ],
  },
  {
    id: '3c5e7g9i-2d4f-49a8-b3c5-e7g9i2d4f6h8',
    projectName: 'Product Launch Workflow',
    createdAt: '2025-01-20',
    lastModified: '2025-03-10',
    activities: [
      {
        id: '7i9k1m3o-5q7s-47u9-b7i9-k1m3o5q7s9u1',
        activityName: 'Market Validation',
        description: 'Validate product market fit and demand',
        inputs: [
          'Market Research',
          'Competitor Analysis',
          'Customer Interviews',
        ],
        outputs: [
          'Market Validation Report',
          'Target Market Segments',
          'Value Proposition',
        ],
        color: '#1890ff',
        assignedUsers: ['Product Manager', 'Market Research Analyst'],
      },
      {
        id: '1m3o5q7s-9u1w-47y3-b1m3-o5q7s9u1w3y5',
        activityName: 'Go-to-Market Planning',
        description: 'Develop comprehensive launch strategy',
        inputs: [
          'Market Validation Report',
          'Value Proposition',
          'Product Roadmap',
        ],
        outputs: [
          'Launch Plan',
          'Marketing Strategy',
          'Sales Enablement Materials',
        ],
        color: '#13c2c2',
        assignedUsers: ['Product Marketing Manager', 'Marketing Director'],
      },
      {
        id: '5q7s9u1w-3y5a-47c7-b5q7-s9u1w3y5a7c9',
        activityName: 'Readiness Assessment',
        description: 'Ensure all teams and systems are ready for launch',
        inputs: ['Launch Plan', 'Product Documentation', 'Training Materials'],
        outputs: ['Readiness Report', 'Risk Assessment', 'Contingency Plans'],
        color: '#faad14',
        assignedUsers: ['Launch Manager', 'Cross-functional Team Leads'],
      },
      {
        id: '9u1w3y5a-7c9e-47g9-b9u1-w3y5a7c9e1g3',
        activityName: 'Launch Execution',
        description: 'Execute the product launch across all channels',
        inputs: ['Readiness Report', 'Launch Plan', 'Marketing Strategy'],
        outputs: ['Launched Product', 'Launch Metrics', 'Customer Feedback'],
        color: '#f5222d',
        assignedUsers: ['Launch Manager', 'Marketing Team', 'Sales Team'],
      },
      {
        id: '3y5a7c9e-1g3i-47k1-b3y5-a7c9e1g3i5k7',
        activityName: 'Post-Launch Review',
        description: 'Analyze launch performance and gather learnings',
        inputs: ['Launch Metrics', 'Customer Feedback', 'Sales Data'],
        outputs: [
          'Launch Performance Report',
          'Lessons Learned',
          'Product Improvement Plan',
        ],
        color: '#722ed1',
        assignedUsers: [
          'Product Manager',
          'Marketing Director',
          'Sales Director',
        ],
      },
    ],
  },
  {
    id: '4d6f8h0j-3e5g-49a9-b4d6-f8h0j3e5g7i9',
    projectName: 'Research Project Workflow',
    createdAt: '2025-02-28',
    lastModified: '2025-03-06',
    activities: [
      {
        id: '8j0l2n4p-6r8t-47u1-b8j0-l2n4p6r8t0u2',
        activityName: 'Research Proposal',
        description: 'Define research questions and methodology',
        inputs: ['Literature Review', 'Gap Analysis', 'Funding Requirements'],
        outputs: [
          'Research Proposal',
          'Research Questions',
          'Methodology Plan',
        ],
        color: '#722ed1',
        assignedUsers: ['Principal Investigator', 'Research Team'],
      },
      {
        id: '2n4p6r8t-0u2w-47y4-b2n4-p6r8t0u2w4y6',
        activityName: 'Experimental Design',
        description: 'Design experiments and data collection procedures',
        inputs: [
          'Research Questions',
          'Methodology Plan',
          'Resource Inventory',
        ],
        outputs: [
          'Experimental Protocol',
          'Data Collection Templates',
          'Analysis Plan',
        ],
        color: '#1890ff',
        assignedUsers: ['Research Scientists', 'Statistician'],
      },
      {
        id: '6r8t0u2w-4y6a-47c8-b6r8-t0u2w4y6a8c0',
        activityName: 'Data Collection',
        description: 'Gather data according to experimental protocol',
        inputs: [
          'Experimental Protocol',
          'Data Collection Templates',
          'Participant Recruitment',
        ],
        outputs: ['Raw Data', 'Collection Logs', 'Preliminary Observations'],
        color: '#13c2c2',
        assignedUsers: ['Research Assistants', 'Lab Technicians'],
      },
      {
        id: '0u2w4y6a-8c0e-47g2-b0u2-w4y6a8c0e2g4',
        activityName: 'Data Analysis',
        description: 'Process and analyze collected data',
        inputs: ['Raw Data', 'Analysis Plan', 'Statistical Methods'],
        outputs: [
          'Analyzed Results',
          'Statistical Reports',
          'Data Visualizations',
        ],
        color: '#52c41a',
        assignedUsers: ['Data Analysts', 'Statistician'],
      },
      {
        id: '4y6a8c0e-2g4i-47k6-b4y6-a8c0e2g4i6k8',
        activityName: 'Research Publication',
        description: 'Prepare and publish research findings',
        inputs: [
          'Analyzed Results',
          'Statistical Reports',
          'Literature Review',
        ],
        outputs: [
          'Research Paper',
          'Presentation Materials',
          'Publication Submission',
        ],
        color: '#eb2f96',
        assignedUsers: ['Principal Investigator', 'Research Team'],
      },
    ],
  },
  {
    id: '5e7g9i1k-4f6h-49a0-b5e7-g9i1k4f6h8j0',
    projectName: 'Event Planning Workflow',
    createdAt: '2025-03-02',
    lastModified: '2025-03-11',
    activities: [
      {
        id: '9k1m3o5q-7s9u-47w3-b9k1-m3o5q7s9u1w3',
        activityName: 'Event Conceptualization',
        description: 'Define event concept, objectives, and scope',
        inputs: ['Business Objectives', 'Target Audience', 'Budget Parameters'],
        outputs: ['Event Concept', 'Event Goals', 'Theme Proposal'],
        color: '#722ed1',
        assignedUsers: ['Event Director', 'Creative Director'],
      },
      {
        id: '3o5q7s9u-1w3y-47a5-b3o5-q7s9u1w3y5a7',
        activityName: 'Venue and Logistics',
        description: 'Secure venue and plan logistical elements',
        inputs: [
          'Event Concept',
          'Attendee Estimates',
          'Technical Requirements',
        ],
        outputs: ['Venue Contract', 'Floor Plan', 'Logistics Schedule'],
        color: '#fa541c',
        assignedUsers: ['Event Coordinator', 'Logistics Manager'],
      },
      {
        id: '7s9u1w3y-5a7c-47e9-b7s9-u1w3y5a7c9e1',
        activityName: 'Program Development',
        description: 'Create event agenda and content',
        inputs: ['Event Goals', 'Theme Proposal', 'Speaker Availability'],
        outputs: ['Event Agenda', 'Session Content', 'Speaker Confirmations'],
        color: '#1890ff',
        assignedUsers: ['Content Director', 'Program Manager'],
      },
      {
        id: '1w3y5a7c-9e1g-47i3-b1w3-y5a7c9e1g3i5',
        activityName: 'Marketing and Promotion',
        description: 'Promote event and manage registrations',
        inputs: ['Event Concept', 'Event Agenda', 'Target Audience'],
        outputs: [
          'Marketing Materials',
          'Registration System',
          'Attendee List',
        ],
        color: '#eb2f96',
        assignedUsers: ['Marketing Manager', 'Communications Specialist'],
      },
      {
        id: '5a7c9e1g-3i5k-47m7-b5a7-c9e1g3i5k7m9',
        activityName: 'Event Execution',
        description: 'Manage event day operations',
        inputs: ['Logistics Schedule', 'Event Agenda', 'Attendee List'],
        outputs: [
          'Event Execution Report',
          'Attendee Feedback',
          'Event Documentation',
        ],
        color: '#fa8c16',
        assignedUsers: ['Event Manager', 'On-site Team'],
      },
    ],
  },
];
