import type { Activity } from '@/interfaces';

export const activityTemplates: Activity[] = [
  {
    id: '8f7e6d5c-4b3a-2d1e-0f9g-8h7i6j5k4l3m',
    activityName: 'Content Creation',
    description: '',
    inputs: [],
    outputs: [],
    color: '#1890ff',
    assignedUsers: [],
  },
  {
    id: '7e6d5c4b-3a2d-1e0f-9g8h-7i6j5k4l3m2n',
    activityName: 'Editorial Review',
    description: '',
    inputs: [],
    outputs: [],
    color: '#52c41a',
    assignedUsers: [],
  },
  {
    id: '6d5c4b3a-2d1e-0f9g-8h7i-6j5k4l3m2n1o',
    activityName: 'Legal Review',
    description: '',
    inputs: [],
    outputs: [],
    color: '#fa8c16',
    assignedUsers: [],
  },
  {
    id: '5c4b3a2d-1e0f-9g8h-7i6j-5k4l3m2n1o0p',
    activityName: 'Final Approval',
    description: '',
    inputs: [],
    outputs: [],
    color: '#f5222d',
    assignedUsers: [],
  },
  {
    id: '4b3a2d1e-0f9g-8h7i-6j5k-4l3m2n1o0p9q',
    activityName: 'Request Submission',
    description: '',
    inputs: [],
    outputs: [],
    color: '#722ed1',
    assignedUsers: [],
  },
  {
    id: '3a2d1e0f-9g8h-7i6j-5k4l-3m2n1o0p9q8r',
    activityName: 'Initial Review',
    description: '',
    inputs: [],
    outputs: [],
    color: '#eb2f96',
    assignedUsers: [],
  },
];
